{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/home/james/PycharmProjects/pymarl/src",
    "dependencies": [
      "munch==2.3.2",
      "numpy==1.15.2",
      "PyYAML==3.13",
      "sacred==0.7.2",
      "torch==0.4.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "main.py",
        "_sources/main_63d7d00072f4e5be0310acb11aa60581.py"
      ],
      [
        "run.py",
        "_sources/run_c4e0d099a01dc64fb105112596df1110.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_aa14e56e60b01dd7a9ddb8e6cdf36b85.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/james/PycharmProjects/venv/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"/home/james/PycharmProjects/pymarl/src/main.py\", line 35, in my_main\n    run(_run, config, _log)\n",
    "  File \"/home/james/PycharmProjects/pymarl/src/run.py\", line 47, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/home/james/PycharmProjects/pymarl/src/run.py\", line 179, in run_sequential\n    transition_loss = learner.train(episode_sample, runner.t_env, episode, mode='transition')\n",
    "  File \"/home/james/PycharmProjects/pymarl/src/learners/new_learner.py\", line 55, in train\n    cur_q_out.append(agent_outs[index.tolist()].view(batch.batch_size, self.args.n_agents))\n",
    "RuntimeError: index 5 is out of bounds for dimension 1 with size 1\n"
  ],
  "heartbeat": "2021-03-10T14:27:13.271785",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz",
    "gpus": {
      "driver_version": "410.48",
      "gpus": [
        {
          "model": "GeForce GTX 1060",
          "persistence_mode": false,
          "total_memory": 6078
        }
      ]
    },
    "hostname": "james-Lenovo-Legion-Y7000-1060",
    "os": [
      "Linux",
      "Linux-4.15.0-136-generic-x86_64-with-Ubuntu-18.04-bionic"
    ],
    "python_version": "3.6.9"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "env_args.map_name=3m"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2021-03-10T14:25:54.886348",
  "status": "FAILED",
  "stop_time": "2021-03-10T14:27:13.288326"
}